### PR TITLE
Build system contd

### PR DESCRIPTION
**Pull request by tlycken**
This fixes the remaining suggestions from the discussion in #7, [except for release notes handling](https://github.com/fsprojects/AProjectHasNoName/pull/7#issuecomment-354959346).

### CODE REVIEW

**Comment by forki** [comment]
can you try to enable the apveyor and travis for this project?

**Comment by tlycken** [comment]
Done! Seems to report back too :)

**Comment by forki** [comment]
nice!

**Comment by tlycken** [comment]
Build is broken because of #14, I believe...

**Comment by forki** [comment]
see #16

**Pull request merged**
