### PR TITLE
fix FAKE download

### PR DESCRIPTION
**Pull request by forki**

### CODE REVIEW

**Comment by tlycken** [comment]
OK, now the Linux builds are failing because they're not looking in the correct directory (although I'm pretty sure it *should* be there). I just managed to reproduce this locally under WSL, so I'll take a look.

**Comment by tlycken** [comment]
Opened #17 against this branch; if that works, we can merge it in here to make sure this works against master too :)

**Comment by forki** [comment]
still not working completely

**Comment by tlycken** [comment]
Hm. It seems the Mono machines don't have `dotnet` installed, and our `build.fsx` apparently fails when determining if it should install it... I'll take a look at it when I get home. In the meantime, feel free to turn off Travis builds if the red ligths discourage you.

**Comment by fbehrens** [comment]
Build is now succeeding on `osx`.
But afterward I have dirty git worktree with a modified `src/.paket/Paket.Restore.targets` 
The `LF` were replace by `CRLF`.
Not sure how to fix this.

**Comment by tlycken** [comment]
Not sure what's appropriate for this file specifically, but line endings are always something you have to handle when you work in a team with different platforms on their workstation :)

Here's a relevant summary of what the problem is and potential ways to deal with it: https://help.github.com/articles/dealing-with-line-endings/#platform-all

Note the platform switch at the top; the Mac instructions might have some hints to get this right on your machine (or maybe I have to do something on mine...)

**Comment by tlycken** [comment]
We could, most likely, force whatever setting we decide on onto all contributors in the `.gitattributes` file much like I did with `.sh` files. It would be better though to make git checkout the files correctly on any platform.

**Comment by tlycken** [comment]
@fbehrens Thanks for testing! If it's working on OSX, I'm pretty confident that the build issues on travis can be fixed in `.travis.yml` and only there.

For the line endings issue, see my comments above.

**Comment by forki** [comment]
https://github.com/SAFE-Stack/SAFE-BookStore/blob/master/build.fsx#L112 allows to download dotnet locally. But it's a FAKE 4 feature that's not fully ported to FAKE 5. Pinging @matthid

**Comment by tlycken** [comment]
@forki [We're doing that too](https://github.com/fsprojects/AProjectHasNoName/blob/2c4825d35d96a72938833aa915a866b7bb0bedb1/src/build.fsx#L27), but I think [this line](https://github.com/fsprojects/AProjectHasNoName/blob/2c4825d35d96a72938833aa915a866b7bb0bedb1/src/build.fsx#L25) is the one causing trouble.

**Comment by fbehrens** [comment]
@tlycken will you pull this into `master` and we'll open a new issue for installing dotnetCore ?

**Pull request merged**
